vim.g.mapleader = " "
local dap, dapui = require("dap"), require("dapui")
vim.keymap.set("n", "<leader>e", vim.cmd.Ex)
local opts = { buffer = bufnr, remap = false }

vim.keymap.set("n", "gd", function()
	vim.lsp.buf.definition()
end, opts)
vim.keymap.set("n", "K", function()
	vim.lsp.buf.hover()
end, opts)
vim.keymap.set("n", "<leader>d", function()
	vim.diagnostic.open_float()
end, opts)
vim.keymap.set("n", "[d", function()
	vim.diagnostic.goto_next()
end, opts)
vim.keymap.set("n", "]d", function()
	vim.diagnostic.goto_prev()
end, opts)
vim.keymap.set("n", "<leader>h", function()
	vim.lsp.buf.code_action()
end, opts)
vim.keymap.set("n", "<leader>r", function()
	vim.cmd("Telescope lsp_references")
end, opts)
vim.keymap.set("n", "<leader>x", function()
	vim.lsp.buf.format()
end, opts)
vim.keymap.set("n", "<leader>t", function()
	vim.cmd("ToggleTerm size=10")
end, opts)
vim.keymap.set("n", "<leader>f", function()
	vim.cmd("w")
	vim.cmd("FormatWrite")
end, opts)
vim.keymap.set("n", "<leader>w", function()
	dap.toggle_breakpoint()
end, opts)
vim.keymap.set("n", "<leader>c", function()
	dap.continue()
end, opts)
vim.keymap.set("n", "<leader>s", function()
	dap.step_into()
end, opts)
vim.keymap.set("n", "<leader>q", function()
	dap.terminate()
end, opts)
vim.keymap.set("n", "<leader>o", function()
	dapui.close()
end, opts)
vim.keymap.set("n", "<leader>k", function()
	dap.up()
end, opts)
vim.keymap.set("n", "<leader>j", function()
	dap.down()
end, opts)
vim.keymap.set("n", "<leader>g", function()
	dap.step_over()
end, opts)
vim.keymap.set("n", "<leader>i", function()
	dapui.eval()
end, opts)
vim.keymap.set("n", "<C-k>", "<C-w><C-k>", opts)
vim.keymap.set("n", "<C-j>", "<C-w><C-j>", opts)
vim.keymap.set("n", "<C-x>", function()
	vim.cmd("bnext")
end, opts)
vim.keymap.set("n", "<C-l>", function()
	vim.cmd("bprev")
end, opts)
vim.keymap.set("n", "<esc>", "<nop>")
